spring.application.name=manojmobiles

spring.datasource.url=jdbc:postgresql://localhost:5432/manojmobiles
spring.datasource.username=postgres
spring.datasource.password=Ankur@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
