package com.api.manojmobiles.service;

import com.api.manojmobiles.dto.brand.BrandRequestDTO;
import com.api.manojmobiles.dto.brand.BrandResponseDTO;
import com.api.manojmobiles.entity.Brand;
import com.api.manojmobiles.exception.BadRequestException;
import com.api.manojmobiles.exception.ResourceNotFoundException;
import com.api.manojmobiles.repository.BrandRepository;
import com.api.manojmobiles.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class BrandService {

    private final BrandRepository brandRepository;
    private final ProductRepository productRepository;

    @Transactional(readOnly = true)
    public org.springframework.data.domain.Page<BrandResponseDTO> getAllBrands(
            org.springframework.data.domain.Pageable pageable) {
        return brandRepository.findAll(pageable)
                .map(this::mapToDTO);
    }

    @Cacheable(value = "brand", key = "#id")
    @Transactional(readOnly = true)
    public BrandResponseDTO getBrandById(UUID id) {
        Brand brand = brandRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Brand not found with id: " + id));
        return mapToDTO(brand);
    }

    @Transactional(readOnly = true)
    public BrandResponseDTO getBrandBySlug(String slug) {
        Brand brand = brandRepository.findBySlug(slug)
                .orElseThrow(() -> new ResourceNotFoundException("Brand not found with slug: " + slug));
        return mapToDTO(brand);
    }

    @CacheEvict(value = { "brands", "brand" }, allEntries = true)
    @Transactional
    public BrandResponseDTO createBrand(BrandRequestDTO request) {
        if (brandRepository.existsByNameIgnoreCase(request.getName())) {
            throw new BadRequestException("Brand with this name already exists");
        }

        Brand brand = Brand.builder()
                .name(request.getName())
                .logo_url(request.getLogoUrl()) // mapping from logoUrl in DTO to logo_url in Entity
                .description(request.getDescription())
                .build();

        Brand savedBrand = brandRepository.save(brand);
        return mapToDTO(savedBrand);
    }

    @CacheEvict(value = { "brands", "brand" }, allEntries = true)
    @Transactional
    public BrandResponseDTO updateBrand(UUID id, BrandRequestDTO request) {
        Brand brand = brandRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Brand not found with id: " + id));

        // Check if name is changed and if new name already exists
        if (!brand.getName().equalsIgnoreCase(request.getName()) &&
                brandRepository.existsByNameIgnoreCase(request.getName())) {
            throw new BadRequestException("Brand with this name already exists");
        }

        brand.setName(request.getName());
        brand.setLogo_url(request.getLogoUrl());
        brand.setDescription(request.getDescription());

        // Slug is auto-generated by @PreUpdate in the entity if we clear it, but here
        // we keep it simple.
        // Actually, @PreUpdate in Brand says: if (slug == null || slug.isBlank()) then
        // generate.
        // So we can force a new slug if name changes by setting slug to null.
        if (!brand.getName().equalsIgnoreCase(request.getName())) {
            brand.setSlug(null);
        }

        Brand updatedBrand = brandRepository.save(brand);
        return mapToDTO(updatedBrand);
    }

    @CacheEvict(value = { "brands", "brand" }, allEntries = true)
    @Transactional
    public void deleteBrand(UUID id) {
        if (!brandRepository.existsById(id)) {
            throw new ResourceNotFoundException("Brand not found with id: " + id);
        }
        productRepository.unlinkBrandFromProducts(id);
        brandRepository.deleteById(id);
    }

    private BrandResponseDTO mapToDTO(Brand brand) {
        return BrandResponseDTO.builder()
                .id(brand.getId())
                .name(brand.getName())
                .logoUrl(brand.getLogo_url())
                .description(brand.getDescription())
                .slug(brand.getSlug())
                .build();
    }
}
